### ISSUE TITLE
Use container solution for covviz installation instead of conda

### ISSUE THREAD

**Issue by ManavalanG** [uab-cgds-worthey/quac#52]
`covviz` is currently not available via bioconda and so we have been using `pip` to install it within conda environment. Current config:

```yaml
name: covviz

channels:
  - conda-forge

dependencies:
  - python==3.8.5
  - pip
  - pip:
      - covviz==1.2.2
```

Using `pip` within conda env is not recommended at all though. When dealing with #49, it became clear that we needed to move away from this solution. 

Since we just need `covviz` and no other tools need to be installed, we can sidestep conda env and instead we can directly use [`covviz` docker container](https://hub.docker.com/r/brwnj/covviz) provided by the tool authors. Note that, we are already using similar setup to install and use `somalier`.
